# Generated by Django 4.2.7 on 2026-02-23 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('task_type', models.CharField(choices=[('study', 'Initial Study'), ('revision', 'Revision'), ('practice', 'Practice Questions')], default='study', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to='content.topic')),
            ],
            options={
                'verbose_name': 'Study Task',
                'verbose_name_plural': 'Study Tasks',
                'ordering': ['scheduled_date', 'topic__order'],
                'unique_together': {('student', 'topic', 'task_type', 'scheduled_date')},
            },
        ),
    ]
