# Generated by Django 4.2.7 on 2026-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_study_time',
            field=models.CharField(choices=[('early_morning', 'Early Morning (5-7 AM)'), ('morning', 'Morning (7-10 AM)'), ('afternoon', 'Afternoon (12-3 PM)'), ('evening', 'Evening (3-6 PM)'), ('night', 'Night (6-9 PM)'), ('late_night', 'Late Night (9 PM+)')], default='morning', max_length=20),
        ),
    ]
